---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  labels:
    type: local
spec:
  capacity:
    storage: 30Mi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/logs/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: monitoring
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
