---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b-deployment
  labels:
    app: app-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
        - name: server
          image: k8s.gcr.io/echoserver:1.4
          resources:
            requests:
              cpu: 0.1
              memory: 256M
            limits:
              cpu: 0.5
              memory: 512M
