---
apiVersion: v1
kind: Namespace
metadata:
  name: product

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c
  namespace: product
  labels:
    app: app-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-c
  template:
    metadata:
      labels:
        app: app-c
    spec:
      containers:
        - name: server
          image: k8s.gcr.io/echoserver:1.4
          resources:
            requests:
              cpu: 0.1
              memory: 256M
